### PR TITLE
Adopt pyproject.toml

### LINKED ISSUE #1571: adopt pyproject.toml
Can be done in 2 steps:

- there should be a minimal `pyproject.toml` in any case, giving build system requirements and backend
- even better, move all metadata from setup.cfg / .py to pyproject.toml (for moin as well as for the misc. other tools used for development)

https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

Example PR from borg: https://github.com/borgbackup/borg/pull/7997

### LINKED ISSUE #1619: drop direct calls to setup.py
Direct invocations of setup.py are deprecated since long, so we should remove these from our scripts, workflows, docs.

Other usage of setup.py is *not* deprecated, but often not needed for pure python projects (as opposed to projects which build C extensions there).

E.g.:
Replace: `python setup.py sdist`
By: `pip install build ; python -m build`

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
Modern python packaging expects to find a `pyproject.toml`, which can also be used to contain configuration information for a lot of python-related tools.

Direct calls to `setup.py` are deprecated. Fixes #1619.

Fixes #1571.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@RogerHaase I put your name/email into maintainer list (as found in git logs).

@UlrichB22 I didn't find a usable email in git logs, so I didn't add you into maintainer list yet.

**Comment by ThomasWaldmann** [comment]
Note: I didn't do much practical testing of this yet, help is appreciated.

**Comment by UlrichB22** [comment]
Regarding babel, please change babel.cfg to

```
[python: **/**.py]
encoding = utf-8

[jinja2: **/templates/**.html]
encoding = utf-8

[jinja2: **/templates/dictionary.js]
# all JS translatable strings must be defined here for jQuery i18n plugin
encoding = utf-8
```

and add following options to the `babel extract` command in `docs/devel/translate.rst`:
```
--project="moin" 
--version="<version>"
```

**Comment by ThomasWaldmann** [comment]
When reviewers think this is ready, please approve.

After that, I'ld like to squash some commits before merging.

**Comment by RogerHaase** [comment]
I tested clone on windows, all OK except for test 3 errors (Cannot create a file when that file already exists:) that did not repeat on 2nd try. This happens occasionally on Windows, fix is to rerun.

    ================================== FAILURES ===================================
    ________________________________ test_load_all ________________________________

    artifact_dir = WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifacts/cli')
    save_all = CompletedProcess(args=['moin', 'save', '-a', '-f', WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifacts/backup.m...d by index rebuild is recommended\r\n2024-02-23 14:05:52,070 INFO moin.cli.maint.serialization:70 Backup finished\r\n')

        def test_load_all(artifact_dir, save_all):
            restore_dir = Path(artifact_dir / 'restore_all')
    >       load(restore_dir, 'backup.moin', artifact_dir)

    C:\Clones\ThomasWaldmann\moin\src\moin\cli\_tests\test_serialization.py:41: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    C:\Clones\ThomasWaldmann\moin\src\moin\cli\_tests\test_serialization.py:26: in load
        restore_dir.mkdir()
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifacts/cli/restore_all')
    mode = 511, parents = False, exist_ok = False

        def mkdir(self, mode=0o777, parents=False, exist_ok=False):
            """
            Create a new directory at this given path.
            """
            try:
    >           self._accessor.mkdir(self, mode)
    E           FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Clones\\ThomasWaldmann\\moin\\_test_artifacts\\cli\\restore_all'

    C:\Users\haase\AppData\Local\Programs\Python\Python310\lib\pathlib.py:1175: FileExistsError
    ____________________________ test_load_default_ns _____________________________

    artifact_dir = WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifacts/cli')
    save_default = CompletedProcess(args=['moin', 'save', '-b', 'default', '-f', WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifac...d by index rebuild is recommended\r\n2024-02-23 14:05:55,219 INFO moin.cli.maint.serialization:70 Backup finished\r\n')

        def test_load_default_ns(artifact_dir, save_default):
            moin_dir, _ = get_dirs('')
            welcome_dir = moin_dir / 'src' / 'moin' / 'help' / 'welcome'
            expected_metas = {}
            for data_fn in welcome_dir.glob('*.meta'):
                with open(data_fn) as f:
                    meta = json.load(f)
                    if meta[NAMESPACE] != '':
                        continue
                    name = meta[NAME][0]
                    expected_metas[name] = meta
            restore_dir = Path(artifact_dir / 'restore_default')
    >       load(restore_dir, 'backup_default.moin', artifact_dir)

    C:\Clones\ThomasWaldmann\moin\src\moin\cli\_tests\test_serialization.py:61: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    C:\Clones\ThomasWaldmann\moin\src\moin\cli\_tests\test_serialization.py:26: in load
        restore_dir.mkdir()
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifacts/cli/restore_default')
    mode = 511, parents = False, exist_ok = False

        def mkdir(self, mode=0o777, parents=False, exist_ok=False):
            """
            Create a new directory at this given path.
            """
            try:
    >           self._accessor.mkdir(self, mode)
    E           FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Clones\\ThomasWaldmann\\moin\\_test_artifacts\\cli\\restore_default'

    C:\Users\haase\AppData\Local\Programs\Python\Python310\lib\pathlib.py:1175: FileExistsError
    ______________________________ test_load_new_ns _______________________________

    artifact_dir = WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifacts/cli')
    save_default = CompletedProcess(args=['moin', 'save', '-b', 'default', '-f', WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifac...d by index rebuild is recommended\r\n2024-02-23 14:05:55,219 INFO moin.cli.maint.serialization:70 Backup finished\r\n')

        def test_load_new_ns(artifact_dir, save_default):
            restore_dir = Path(artifact_dir / 'restore_new_ns')
    >       load(restore_dir, 'backup_default.moin', artifact_dir, ['-o', '', '-n', 'help-en'])

    C:\Clones\ThomasWaldmann\moin\src\moin\cli\_tests\test_serialization.py:91: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    C:\Clones\ThomasWaldmann\moin\src\moin\cli\_tests\test_serialization.py:26: in load
        restore_dir.mkdir()
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = WindowsPath('C:/Clones/ThomasWaldmann/moin/_test_artifacts/cli/restore_new_ns')
    mode = 511, parents = False, exist_ok = False

        def mkdir(self, mode=0o777, parents=False, exist_ok=False):
            """
            Create a new directory at this given path.
            """
            try:
    >           self._accessor.mkdir(self, mode)
    E           FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Clones\\ThomasWaldmann\\moin\\_test_artifacts\\cli\\restore_new_ns'

    C:\Users\haase\AppData\Local\Programs\Python\Python310\lib\pathlib.py:1175: FileExistsError

**Comment by RogerHaase** [comment]
Not a new problem. Windows seems to have problems dealing with tests that delete a file and then recreate a file with same name. Happens around 1 in 50 or 100 tests. Cannot reproduce.

**Comment by ThomasWaldmann** [comment]
@RogerHaase OK, guess that should be in a ticket then, not in this PR. I remember we have seen very strange windows fs effects in the past, too.

**Comment by UlrichB22** [comment]
The translation with pybabel works fine now. 
I think you will test all the packaging stuff.

**Comment by ThomasWaldmann** [comment]
I manually and automatically compared the sdist *.tgz files produced by this PR and master branch - there were no unexpected differences.

So, if there is nothing else, guess this is good to merge.

**Comment by ThomasWaldmann** [comment]
Squashed some fix commits and force-pushed. Ready AFAIAC.

**Pull request merged**
