### PR TITLE
Tests: add test case for markdown tables

### PR DESCRIPTION
**Pull request by wagner-intevation**
the markdown test cases were missing tests for the table extension

### CODE REVIEW

**Comment by wagner-intevation** [comment]
I don't understand why the tests fail
```
        File "/tmp/pip-build-env-73m3_uf_/normal/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 63, in write_version_files
          dump_version(
        File "/tmp/pip-build-env-73m3_uf_/normal/lib/python3.10/site-packages/setuptools_scm/_integration/dump_version.py", line 36, in dump_version
          assert not write_to.is_absolute(), f"{write_to=}"
      AssertionError: write_to=PosixPath('/home/runner/work/moin/moin/src/moin/_version.py')
```
Please give me a hint of where the issue originates from.

**Comment by UlrichB22** [comment]
I think this error is a general problem and not related to you changes. I will compare the CI logs with the logs of the latest successful run.

**Comment by wagner-intevation** [comment]
rebased on master

**Comment by wagner-intevation** [comment]
now the tests succeed as expected :)

**Pull request merged**
