### PR TITLE
Add various missing German translations, consolidate and simplify existing ones

### PR DESCRIPTION
**Pull request by wagner-intevation**
Add some missing strings
Simplify a few translations
and consolidate the mixed translation of namespace: one occurrence of it was translated, others weren't. So translate all for consistency

### CODE REVIEW

**Comment by UlrichB22** [comment]
Hi Sebastian,
thanks for providing additional translations. Here are some typos or enhancements with line numbers:

- 1350: ... kann, ItemID =
- 1492: des Items
- 1723: Prüfe den Namen!
- 1753: Schlüssel (oder Key)
- 1771: schreib mir
- 2001: finden
- 2035: Klicke Link 'Hervorheben' in den Item-Ansichten, um den reinen Text zu sehen.
- 2769: Wort 'um' ist doppelt

What is your opinion about 'Abbestellen' instead of 'Deabonnieren'?

After updating and before commiting please run following command to create standard line-breaks:
`python setup.py update_catalog -l de`

The line breaks should then appear after about 120 characters. This prevents the lines from changing the next time someone wants to update the translations.

**Comment by UlrichB22** [comment]
Now its line 1727, it should be something like:
`msgstr "Icon wird nicht dargestellt, Prüfen Sie den Namen"`

**Comment by wagner-intevation** [comment]
> Now its line 1727, it should be something like: `msgstr "Icon wird nicht dargestellt, Prüfen Sie den Namen"`

The English string does not contain that phrase?

**Comment by UlrichB22** [comment]
It is fixed and merged already:
https://github.com/moinwiki/moin/blob/409d3f48b470d3e0f49f17984879af21d8c24e85/src/moin/translations/de/LC_MESSAGES/messages.po#L1716

**Comment by wagner-intevation** [comment]
Oh, okay, I misunderstood the English text. I read "'verify name' is valid", i.e. 'verify name' as some label for an internal process or method, not as a prompt to the user.

**Pull request merged**
