### PR TITLE
167 scrapy test

### PR DESCRIPTION
**Pull request by bylsmad**
test_scrapy_crawl starts moin dev server on port 9080
  with sample wiki and crawls the site
  validating response codes
  for src href data-href and data attributes

### CODE REVIEW

**Review by UlrichB22 — CHANGES_REQUESTED** [review]
flask-script is no longer used, moin now uses flask cli and click. The changes were developed in the last weeks and merged today. Please adjust run_moin. 

Using sample-backup is fine for the moment but it is planned to remove the file in future, see https://github.com/moinwiki/moin/issues/1155. Most of these items can also be found in help-en and help-common.

**Comment by RogerHaase** [comment]
In ref_checker.py there is:

     """shamelessly stolen from https://www.linode.com/docs/guides/use-scrapy-to-extract-data-from-html-tags/"""

which raises the issue of whether we can pull code from a commercial website? A guess is appx 20 lines of code were copied. 

In this case the copied code is part of a how-to that is intended to be copied. Users are encouraged to create an account, but there is no requirement to do so. There is no copyright notice nor license on the source web page nor on similar pages, As there is a reference to the origin of the code we should be OK. But...

bylsmad: are you a Linode or Akamai customer? Can you ask if is OK to copy code from the guides into open source software on the Linode Community  Forum?

**Comment by bylsmad** [comment]
yes I am a linode customer, I've submitted a help ticket inquiring about use of their guide code in moin

also, couple things still in progreess here

1. I just figured out the intermittent failure with a 404 for http://127.0.0.1:9080:/rst it has to do with the breadcrumbs created if scrapy keeps crawling after hitting the 404 for http://127.0.0.1:9080:/rst/MissingItem
2. found out that on the windows build I was using an incompatible signal to kill the moin server (my dev box is debian) so will be experimenting with the github action in my fork to get test passing on windows
3. question - I've found that harvesting the crawl.log crawl.csv and server.log as an artifact in the github action is quite helpful, is it ok for me to add this to the ci.yml for master?

**Comment by bylsmad** [comment]
this pull request not fully ready for review I went ahead with archiving the crawl logs in the github action and did get the test passing on windows

I'd like this bit to get the code in this pull merged after that I'm thinking that the next steps are:

4. resolve KNOWN_ISSUES which only require simple edits to help/en files
5. resolve KNOWN_ISSUES which arise from missing pages such as /users/Home by creating them in run_moin.py
6. resolve any remaining KNOWN_ISSUES which represent bugs in converters
7. execute run_moin.py with coverage and do the crawl, add content to help/en to increase code coverage in converters

thoughts?  other next steps?  any other validations which would be nice to add to the spider?

**Comment by bylsmad** [comment]
ready for review, really gonna stop making changes to the test now

while working on reviving ui_tests, I came across pytest package scope fixtures, rewrote the CrawlResults class more clearly using  fixtures in conftest.py

**Comment by bylsmad** [comment]
closing this pull req, will rebase, add suggested changes and resubmit under #1375

**Pull request closed without merging**
