### PR TITLE
Add "tag" parameter to ItemList macro

### PR DESCRIPTION
**Pull request by oSquat**
The inverse of "skiptag", allow for a "tag" parameter so that ItemList() only displays items that have been tagged accordingly.

`<<ItemList(tag="foo")>>`

### CODE REVIEW

**Comment by oSquat** [comment]
This looks like a linter picked some subtle formatting disagreements. If there's something I can do to facilitate the process please offer guidance.

**Comment by RogerHaase** [comment]
Thanks for helping.

You must push updates to fix the styling requirements. I think the checks will automatically rerun with every update you make.

**Comment by oSquat** [comment]
Did that do it? All I did was synchronize my fork preparing to make the prescribed fixes. Thank you for your assistance, I've never experienced this workflow before.

**Comment by UlrichB22** [comment]
There is a blank / space character at the end of line 432 in docs/user/creolewiki.rst.
This may be the reason for the failing check. Please try to add a commit to the PR without this blank.

**Comment by UlrichB22** [comment]
@oSquat, Please also consider to add the pre-commit hook as described in #1672.

**Comment by oSquat** [comment]
I hope that's it. @UrlrichB22, thanks for pointing out the issue and I'll have to work on getting my running copy of Moin synchronized to my fork. I made & tested these changes on an installation that's a little outdated and then edited them into a fork through the github UI which isn't a great experience.

**Comment by RogerHaase** [comment]
Thanks for helping. In the future, it is best practice to create a branch for an update rather than making changes directly to master.

**Comment by oSquat** [comment]
Thanks for your patience and helping me get this through! I'll get a real dev instance setup and branch in the future. I can't imagine it could go less smoothy than this.

**Comment by UlrichB22** [comment]
We appreciate your support. You can find more information about the development of moin 2.0 at https://moin-20.readthedocs.io/en/latest/devel/development.html.

**Pull request merged**
