### PR TITLE
line endings change for .data and .meta, #1390

### PR DESCRIPTION
**Pull request by bylsmad**
github action windows host uses core.autocrlf=true which causes the checked out files to have \r\n if they are text

converting to binary makes them \r\n everywhere, also makes the size in metadata match up

TIP: for git diff do `git diff --text` when you have changes

### CODE REVIEW

**Comment by RogerHaase** [comment]
Before pushing changes to help files, `moin maint-reduce-revisions` must be run to avoid #1398. 

If you fix this I will kill PR 1399

**Comment by bylsmad** [comment]
@RogerHaase new commit is added after running the moin maint-reduce-revisions, the parentids appear to be gone

**Comment by RogerHaase** [comment]
One of the tools I use is Git for Windows that provides GIT GUI. For binary files GIT GUI says:

    Binary files a/src/moin/help/en/Home%2fsubitem.meta and b/src/moin/help/en/Home%2fsubitem.meta differ

which is not helpful in reviewing the changes before a commit > push.

TortoiseGit provides a diff that shows line by line changes for binary files but is more tedious to use. Are there similar issues with linux/mac tools?

A second concern is the .gitattributes file. Is "*.data binary" specific enough? Could it be "*/help/*.data binary" or similar?

Is there an alternative way to write the new tests without making the help .meta and ,data files binary?

**Comment by RogerHaase** [comment]
My merge of PR1399 created above conflicts.

**Pull request closed without merging**
