### PR TITLE
Update to python3.6

### PR DESCRIPTION
**Pull request by eamanu**
Bump to py3.6. This is in WIP but the first step to bump to py3.6

I update the quickinstall.py. Remove the virtualenv requirements to start use
venv.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
See the issue about the py36 upgrade. Qubes OS is still on debian stretch, so py35 is the default here.

**Comment by ThomasWaldmann** [comment]
https://docs.python.org/3.5/library/venv.html

also it seems that `venv` would also work for 3.5, so why did you mix raising the python requirement and moving from virtualenv to venv?

**Comment by ThomasWaldmann** [comment]
Also, your PR should be against master now, because we have merged the py3 branch into master already.

Guess it would be best if you first do a PR with everything that works on 3.5 also and delay the 3.6 stuff until later.

**Comment by eamanu** [comment]
Hi @ThomasWaldmann  Thanks for the feedback. 

> Guess it would be best if you first do a PR with everything that works on 3.5 also and delay the 3.6 stuff until later.

Ok I will take a look on the code to help on it. 

> also it seems that venv would also work for 3.5, so why did you mix raising the python requirement and moving from virtualenv to venv?

hmm yes. I think that we can move to venv, this way we avoid the requirement to install other module (virtualenv), because py3 come with venv module.

**Pull request closed without merging**
