### PR TITLE
import19 must not migrate email links when migrating href links to /u…

### PR DESCRIPTION
**Pull request by RogerHaase**
…sers/

### CODE REVIEW

**Comment by UlrichB22** [comment]
Sorry, cannot reproduce. Please give an example of a typical raw line from a moin19 wiki that is converted incorrectly.

**Comment by RogerHaase** [comment]
A moin 1.x page must have a link  and a mailto to trigger the bug.

If a page has a link then code near line 164 in import19.py calls
migrate_users_links:

            if len(itemlinks2chg) > 0:
                migrate_users_links(dom, itemlinks2chg)

Then near line 472:

    for node in dom.iter_elements_tree():
        # do not change email nodes, these have
type(node.attrib[xlink.href]) == 'string'
        if node.tag.name == 'a' and not isinstance(node.attrib[xlink.href],
str):
            path_19 = str(node.attrib[xlink.href].path)

The old code throws an error setting path_19.

**Comment by UlrichB22** [comment]
Can you please add a piece of moin markup that gives the error? This would help me to understand and reproduce the issue. Maybe I can also add a test for it.

**Comment by RogerHaase** [comment]
[[SomePage]]

Email: ***@***.***

**Pull request merged**
